// app/layout.jsx atau app/root-layout.jsx
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/sessionwrapper/sessionwrapper"; // pakai wrapper client

export const metadata = {
  title: "HS Caffe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-polygon flex flex-col min-h-screen justify-between">
        <SessionWrapper>
          <Navbar />
          <div className="mt-20">{children}</div>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
